#pragma once
#include "resource.h"

static const IconEntry kItems_Crystal[] = {
    {L"Ruby Crystal[F]",        RUBY_CRYSTAL_F},
    {L"Topaz Crystal[F]",       TOPAZ_CRYSTAL_F},
    {L"Amethyst Crystal[F]",    AMETHYST_CRYSTAL_F},
    {L"Diamond Crystal[F]",     DIAMOND_CRYSTAL_F},
    {L"Pearl Crystal[F]",       PEARL_CRYSTAL_F},
    {L"Sapphire Crystal[F]",    SAPPHIRE_CRYSTAL_F},
    {L"Ruby Crystal[E]",        RUBY_CRYSTAL_E},
    {L"Topaz Crystal[E]",       TOPAZ_CRYSTAL_E},
    {L"Amethyst Crystal[E]",    AMETHYST_CRYSTAL_E},
    {L"Diamond Crystal[E]",     DIAMOND_CRYSTAL_E},
    {L"Pearl Crystal[E]",       PEARL_CRYSTAL_E},
    {L"Sapphire Crystal[E]",    SAPPHIRE_CRYSTAL_E},
    {L"Ruby Crystal[D]",        RUBY_CRYSTAL_D},
    {L"Topaz Crystal[D]",       TOPAZ_CRYSTAL_D},
    {L"Amethyst Crystal[D]",    AMETHYST_CRYSTAL_D},
    {L"Diamond Crystal[D]",     DIAMOND_CRYSTAL_D},
    {L"Pearl Crystal[D]",       PEARL_CRYSTAL_D},
    {L"Sapphire Crystal[D]",    SAPPHIRE_CRYSTAL_D},
    {L"Ruby Crystal[C]",        RUBY_CRYSTAL_C},
    {L"Topaz Crystal[C]",       TOPAZ_CRYSTAL_C},
    {L"Amethyst Crystal[C]",    AMETHYST_CRYSTAL_C},
    {L"Diamond Crystal[C]",     DIAMOND_CRYSTAL_C},
    {L"Pearl Crystal[C]",       PEARL_CRYSTAL_C},
    {L"Sapphire Crystal[C]",    SAPPHIRE_CRYSTAL_C},
    {L"Ruby Crystal[B]",        RUBY_CRYSTAL_B},
    {L"Topaz Crystal[B]",       TOPAZ_CRYSTAL_B},
    {L"Amethyst Crystal[B]",    AMETHYST_CRYSTAL_B},
    {L"Diamond Crystal[B]",     DIAMOND_CRYSTAL_B},
    {L"Pearl Crystal[B]",       PEARL_CRYSTAL_B},
    {L"Sapphire Crystal[B]",    SAPPHIRE_CRYSTAL_B},
    {L"Ruby Crystal[A]",        RUBY_CRYSTAL_A},
    {L"Topaz Crystal[A]",       TOPAZ_CRYSTAL_A},
    {L"Amethyst Crystal[A]",    AMETHYST_CRYSTAL_A},
    {L"Diamond Crystal[A]",     DIAMOND_CRYSTAL_A},
    {L"Pearl Crystal[A]",       PEARL_CRYSTAL_A},
    {L"Sapphire Crystal[A]",    SAPPHIRE_CRYSTAL_A},
    {L"Ruby Crystal[S1]",       RUBY_CRYSTAL_S1},
    {L"Topaz Crystal[S1]",      TOPAZ_CRYSTAL_S1},
    {L"Amethyst Crystal[S1]",   AMETHYST_CRYSTAL_S1},
    {L"Diamond Crystal[S1]",    DIAMOND_CRYSTAL_S1},
    {L"Pearl Crystal[S1]",      PEARL_CRYSTAL_S1},
    {L"Sapphire Crystal[S1]",   SAPPHIRE_CRYSTAL_S1},
    {L"Ruby Crystal[S2]",       RUBY_CRYSTAL_S2},
    {L"Topaz Crystal[S2]",      TOPAZ_CRYSTAL_S2},
    {L"Amethyst Crystal[S2]",   AMETHYST_CRYSTAL_S2},
    {L"Diamond Crystal[S2]",    DIAMOND_CRYSTAL_S2},
    {L"Pearl Crystal[S2]",      PEARL_CRYSTAL_S2},
    {L"Sapphire Crystal[S2]",   SAPPHIRE_CRYSTAL_S2},
};

static constexpr size_t kItems_Crystal_Count = _countof(kItems_Crystal);