#include "RecipeModel.h"
#include "RecipeModules.h"

using RecipesDB::Mat;
using RecipesDB::Sub;
using RecipesDB::Tool;
using RecipesDB::AddRecipe;

using namespace recipes;

void recipes::RegisterBaseMaterials() {
    // Food
    RecipesDB::Add(Recipe{ L"Rice", {} });
    RecipesDB::Add(Recipe{ L"Radish", {} });
    RecipesDB::Add(Recipe{ L"Parsley", {} });
    RecipesDB::Add(Recipe{ L"Shitake Mushroom", {} });
    RecipesDB::Add(Recipe{ L"Mung Bean", {} });
    RecipesDB::Add(Recipe{ L"Potato", {} });
    RecipesDB::Add(Recipe{ L"Onion", {} });
    RecipesDB::Add(Recipe{ L"Cucumber", {} });
    RecipesDB::Add(Recipe{ L"Carrot", {} });
    RecipesDB::Add(Recipe{ L"Garlic", {} });
    RecipesDB::Add(Recipe{ L"Bean", {} });
    RecipesDB::Add(Recipe{ L"Sesame Seed", {} });
    RecipesDB::Add(Recipe{ L"Wheat", {} });
    RecipesDB::Add(Recipe{ L"Chicken", {} });
    RecipesDB::Add(Recipe{ L"Pork", {} });
    RecipesDB::Add(Recipe{ L"Beef", {} });
    RecipesDB::Add(Recipe{ L"Honey", {} });
    // Medicine
    RecipesDB::Add(Recipe{ L"Ginseng", {} });
    RecipesDB::Add(Recipe{ L"Horn", {} });
    RecipesDB::Add(Recipe{ L"Madder Seed", {} });
    RecipesDB::Add(Recipe{ L"Adlay Seed", {} });
    RecipesDB::Add(Recipe{ L"Bean Root", {} });
    RecipesDB::Add(Recipe{ L"Mushroom", {} });
    RecipesDB::Add(Recipe{ L"Button Mushroom", {} });
    RecipesDB::Add(Recipe{ L"Orange Peel", {} });
    RecipesDB::Add(Recipe{ L"Lily Root", {} });
    RecipesDB::Add(Recipe{ L"Okara", {} });
    RecipesDB::Add(Recipe{ L"Walnut Root", {} });
    RecipesDB::Add(Recipe{ L"Love Vine", {} });
    // Book
    RecipesDB::Add(Recipe{ L"Medicine Prescription[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Medicine Prescription[INT]", {} });
    RecipesDB::Add(Recipe{ L"Medicine Prescription[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Armor Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Armor Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Armor Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Helmet Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Helmet Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Helmet Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Sword Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Sword Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Sword Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Spear Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Spear Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Spear Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Axe Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Axe Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Axe Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Cane Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Cane Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Cane Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Bow Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Bow Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Bow Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Gun Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Gun Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Gun Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Capture Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Capture Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Capture Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Farming Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Farming Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Farming Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Mining Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Mining Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Mining Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Recipes[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Recipes[INT]", {} });
    RecipesDB::Add(Recipe{ L"Recipes[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Sword Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Sword Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Sword Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Spear Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Spear Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Spear Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Bow Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Bow Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Bow Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Axe Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Axe Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Axe Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Gun Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Gun Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Gun Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Cane Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Cane Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Cane Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Shoe Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Shoe Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Shoe Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Belt Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Belt Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Belt Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Horse Training[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Horse Training[INT]", {} });
    RecipesDB::Add(Recipe{ L"Horse Training[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Ironware Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Ironware Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Ironware Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Tool Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Tool Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Tool Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Summon Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Summon Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Summon Technique[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Fishing Technique[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Fishing Technique[INT]", {} });
    RecipesDB::Add(Recipe{ L"Crystal Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Crystal Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Crystal Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Clothes Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Clothes Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Clothes Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Hat Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Hat Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Hat Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Cloak Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Cloak Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Cloak Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Ring Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Ring Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Ring Manufacture[ADV]", {} });
    RecipesDB::Add(Recipe{ L"Necklace Manufacture[BGN]", {} });
    RecipesDB::Add(Recipe{ L"Necklace Manufacture[INT]", {} });
    RecipesDB::Add(Recipe{ L"Necklace Manufacture[ADV]", {} });
    // Mineral
    RecipesDB::Add(Recipe{ L"Coal", {} });
    RecipesDB::Add(Recipe{ L"Iron Ore", {} });
    RecipesDB::Add(Recipe{ L"Iron", {} });
    RecipesDB::Add(Recipe{ L"Steel", {} });
    RecipesDB::Add(Recipe{ L"Copper", {} });
    RecipesDB::Add(Recipe{ L"Brass", {} });
    RecipesDB::Add(Recipe{ L"Clay-slate Stone", {} });
    RecipesDB::Add(Recipe{ L"Gold Ore", {} });
    RecipesDB::Add(Recipe{ L"Gold Bar", {} });
    RecipesDB::Add(Recipe{ L"Silver Ore", {} });
    RecipesDB::Add(Recipe{ L"Silver Bar", {} });
    RecipesDB::Add(Recipe{ L"Aquamarine", {} });
    RecipesDB::Add(Recipe{ L"Topaz", {} });
    RecipesDB::Add(Recipe{ L"Jade", {} });
    RecipesDB::Add(Recipe{ L"Clay", {} });
    RecipesDB::Add(Recipe{ L"Sulfur", {} });
    RecipesDB::Add(Recipe{ L"Limestone", {} });
    RecipesDB::Add(Recipe{ L"Pearl", {} });
    RecipesDB::Add(Recipe{ L"Amber", {} });
    RecipesDB::Add(Recipe{ L"Coral", {} });
    RecipesDB::Add(Recipe{ L"Amethyst", {} });
    RecipesDB::Add(Recipe{ L"Diamond", {} });
    RecipesDB::Add(Recipe{ L"Ruby", {} });
    RecipesDB::Add(Recipe{ L"Fire Stone", {} });
    RecipesDB::Add(Recipe{ L"Water Stone", {} });
    RecipesDB::Add(Recipe{ L"Blessing Stone", {} });
    RecipesDB::Add(Recipe{ L"Blue Stone Piece", {} });
    RecipesDB::Add(Recipe{ L"Red Stone Piece", {} });
    RecipesDB::Add(Recipe{ L"Golden Stone Piece", {} });
    RecipesDB::Add(Recipe{ L"Black Stone", {} });
    RecipesDB::Add(Recipe{ L"Titanium", {} });
    RecipesDB::Add(Recipe{ L"Bronze", {} });
    RecipesDB::Add(Recipe{ L"Lead", {} });
    RecipesDB::Add(Recipe{ L"Cobalt", {} });
    RecipesDB::Add(Recipe{ L"White Gold", {} });
    // Wood
    RecipesDB::Add(Recipe{ L"Pine", {} });
    RecipesDB::Add(Recipe{ L"Paper Ingredient", {} });
    RecipesDB::Add(Recipe{ L"Bamboo", {} });
    RecipesDB::Add(Recipe{ L"Oak", {} });
    RecipesDB::Add(Recipe{ L"Charcoal", {} });
    RecipesDB::Add(Recipe{ L"Straw", {} });
    RecipesDB::Add(Recipe{ L"Resin", {} });
    RecipesDB::Add(Recipe{ L"Peg", {} });
    RecipesDB::Add(Recipe{ L"Mahogany", {} });
    // Fabrics
    RecipesDB::Add(Recipe{ L"Cowhide", {} });
    RecipesDB::Add(Recipe{ L"Silk", {} });
    RecipesDB::Add(Recipe{ L"Satin", {} });
    RecipesDB::Add(Recipe{ L"Ramie", {} });
    RecipesDB::Add(Recipe{ L"Premium Silk", {} });
    RecipesDB::Add(Recipe{ L"Thread Bobbin", {} });
    RecipesDB::Add(Recipe{ L"Embroidered Thread Bobbin", {} });
    RecipesDB::Add(Recipe{ L"Gold Thread", {} });
    RecipesDB::Add(Recipe{ L"Silver Thread", {} });
    RecipesDB::Add(Recipe{ L"Cotton", {} });
    RecipesDB::Add(Recipe{ L"Silk Thread", {} });
    RecipesDB::Add(Recipe{ L"Blue Thread", {} });
    RecipesDB::Add(Recipe{ L"Aramid", {} });
    RecipesDB::Add(Recipe{ L"Spiky Silk", {} });
    RecipesDB::Add(Recipe{ L"Black Silk", {} });
    RecipesDB::Add(Recipe{ L"Dinosaur Leather", {} });
    // Marine Products
    RecipesDB::Add(Recipe{ L"Salt", {} });
    RecipesDB::Add(Recipe{ L"Worm", {} });
    RecipesDB::Add(Recipe{ L"Sea Slug", {} });
    RecipesDB::Add(Recipe{ L"Abalone", {} });
    RecipesDB::Add(Recipe{ L"Crucian Carp", {} });
    RecipesDB::Add(Recipe{ L"Catfish", {} });
    RecipesDB::Add(Recipe{ L"Carp", {} });
    RecipesDB::Add(Recipe{ L"Octopus", {} });
    RecipesDB::Add(Recipe{ L"Prawn", {} });
    RecipesDB::Add(Recipe{ L"Eel", {} });
    RecipesDB::Add(Recipe{ L"Mackerel", {} });
    // Crystal
    RecipesDB::Add(Recipe{ L"crystal additive", {} });
    // Mixture
    RecipesDB::Add(Recipe{ L"Lithium", {} });
    RecipesDB::Add(Recipe{ L"Argon", {} });
    RecipesDB::Add(Recipe{ L"Selenium", {} });
    RecipesDB::Add(Recipe{ L"Rubidium", {} });
    RecipesDB::Add(Recipe{ L"Strontium", {} });
    RecipesDB::Add(Recipe{ L"Cadium", {} });
    RecipesDB::Add(Recipe{ L"Fradium", {} });
    RecipesDB::Add(Recipe{ L"Strange unattributable Powder", {} });
    RecipesDB::Add(Recipe{ L"Strange Fire Powder", {} });
    RecipesDB::Add(Recipe{ L"Strange Water Powder", {} });
    RecipesDB::Add(Recipe{ L"Strange Land Powder", {} });
    RecipesDB::Add(Recipe{ L"Strange Wind Powder", {} });
    RecipesDB::Add(Recipe{ L"Mysterical unattributable Powder", {} });
    RecipesDB::Add(Recipe{ L"Mysterical Fire Powder", {} });
    RecipesDB::Add(Recipe{ L"Mysterical Water Powder", {} });
    RecipesDB::Add(Recipe{ L"Mysterical Land Powder", {} });
    RecipesDB::Add(Recipe{ L"Mysterical Wind Powder", {} });
    RecipesDB::Add(Recipe{ L"Illusionary unattributable Powder", {} });
    RecipesDB::Add(Recipe{ L"Illusionary Fire Powder", {} });
    RecipesDB::Add(Recipe{ L"Illusionary Water Powder", {} });
    RecipesDB::Add(Recipe{ L"Illusionary Land Powder", {} });
    RecipesDB::Add(Recipe{ L"Illusionary Wind Powder", {} });
    // Other
    RecipesDB::Add(Recipe{ L"Animal Bones", {} });
    RecipesDB::Add(Recipe{ L"Animal Fur", {} });
    RecipesDB::Add(Recipe{ L"Feather", {} });
    RecipesDB::Add(Recipe{ L"Snowball", {} });
    RecipesDB::Add(Recipe{ L"Poisonous Bottle", {} });
    RecipesDB::Add(Recipe{ L"Sorcerer's eye", {} });
    RecipesDB::Add(Recipe{ L"Skeleton Bat Tooth", {} });
    RecipesDB::Add(Recipe{ L"Ivory", {} });
}